# Generated by Django 3.0.5 on 2020-04-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_image',
            field=models.ImageField(default='', upload_to='analysis/images'),
        ),
    ]
