# Generated by Django 3.0.5 on 2020-04-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20200407_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(default=0),
        ),
    ]
