# Generated by Django 3.0.5 on 2020-04-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='month',
        ),
        migrations.AddField(
            model_name='document',
            name='monthnumber',
            field=models.IntegerField(default=1),
        ),
    ]
